name: myune_music
description: Android edition of the Myune Music local player.
publish_to: none
version: 0.9.3+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  file_picker: ^10.3.10
  uuid: ^4.5.1
  path: ^1.9.1
  system_fonts: ^1.0.1
  colorgram: ^2.0.0
  crypto: ^3.0.3
  http: ^1.4.0
  window_manager: ^0.5.1
  pinyin: ^3.3.0
  mpv_audio_kit: ^0.4.2
  hotkey_manager: ^0.2.3
  silky_scroll: ^2.6.4
  rxdart: ^0.28.0
  rust_lib_myune_music:
    path: rust_builder
  flutter_rust_bridge: 2.10.0
  mesh_gradient: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - img/
